language: android
android:
  components:
    # 使用最新的Android SDK Tools
    - tools
    - platform-tools

    # 设置构建Android项目的构建工具版本
    - build-tools-26.0.1

    # 设置Android项目构建的目标版本
    - android-25

    # 添加必要的组件
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
before_install:
    # 添加保存证书的文件夹
    - mkdir "$ANDROID_HOME/licenses" || true
    # 把证书信息添加到证书文件中
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
before_script:
    - chmod +x gradlew
script:
    - "./gradlew assembleRelease"
deploy:
    provider: releases
    user: "taowenyin"
    password: "05200902"
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true